name: android-maestro-tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run UI Tests with Maestro
        uses: theolm/maestro-run@v0.2.0-alpha
        with:
          apk-path: "app.apk"
          test-path: "test.yml"
          emulator-api: "34"
          emulator-profile: "pixel_8_pro"